name: Deploy API Docs

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker image
      run: |
        docker build -t myorg/swagger-ui:latest .
        docker run --rm -v $(pwd)/docs:/docs swaggerapi/swagger-ui-generator /docs/swagger.yaml /docs/index.html

    - name: Deploy Docs
      run: |
        ./scripts/deploy-docs.sh
